name: CI 

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build sp1.nix
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix build .#cargo-prove -L --accept-flake-config
      - run: nix build .#succinct-rust -L --accept-flake-config
      - run: nix build .#sp1-home -L --accept-flake-config
      - run: nix build .#rustup-shim -L --accept-flake-config

  test:
    name: Test template dev shell
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Replace sp1.nix URL with local path
        run: |
          sed -i 's|url = "github:argumentcomputer/sp1.nix"|url = "path:../.."|' flake.nix
          nix flake update sp1 --accept-flake-config
        working-directory: ${{ github.workspace }}/templates/hello-world
      - run: nix develop --accept-flake-config --command bash -c "cd script && cargo run --release -- --prove"
        working-directory: ${{ github.workspace }}/templates/hello-world
        env:
          RUST_LOG: info
